import js from '@eslint/js'
import eslintConfigPrettier from 'eslint-config-prettier'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

export default tseslint.config(
    // `src-tauri/workers` is generated by `npm run build:workers`: whole dependency graphs inlined
    // into one file each. Linting them lints Pi and its dependencies.
    {ignores: ['dist', 'node_modules', 'src-tauri/target', 'src-tauri/gen', 'src-tauri/workers']},
    {
        files: ['**/*.{ts,tsx}'],
        extends: [
            js.configs.recommended,
            ...tseslint.configs.strictTypeChecked,
            ...tseslint.configs.stylisticTypeChecked,
            eslintConfigPrettier
        ],
        languageOptions: {
            sourceType: 'module',
            ecmaVersion: 2024,
            globals: globals.browser,
            parserOptions: {
                tsconfigRootDir: import.meta.dirname,
                projectService: true
            }
        },
        rules: {
            '@typescript-eslint/no-unsafe-call': 'warn',
            '@typescript-eslint/no-unsafe-member-access': 'warn',
            '@typescript-eslint/require-await': 'warn',
            '@typescript-eslint/no-unsafe-argument': 'warn',
            '@typescript-eslint/no-misused-promises': 'warn',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                {
                    args: 'all',
                    argsIgnorePattern: '^_',
                    caughtErrors: 'all',
                    caughtErrorsIgnorePattern: '^_',
                    destructuredArrayIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    ignoreRestSiblings: true
                }
            ],
            '@typescript-eslint/unbound-method': 'warn',
            '@typescript-eslint/no-floating-promises': 'warn',
            '@typescript-eslint/no-explicit-any': 'error',
            'no-empty': ['error', {allowEmptyCatch: true}],
            'linebreak-style': ['error', 'unix'],
            quotes: ['error', 'single', {allowTemplateLiterals: true, avoidEscape: true}],
            semi: ['error', 'never'],
            'no-tabs': 'off',
            'object-curly-spacing': ['error', 'never'],
            'array-bracket-spacing': ['error', 'never'],
            'computed-property-spacing': ['error', 'never'],
            'brace-style': ['error', '1tbs'],
            'keyword-spacing': 'error',
            'eol-last': 'error',
            'no-trailing-spaces': 'error',
            'no-redeclare': 'error',
            'no-shadow': ['error', {allow: ['_']}],
            camelcase: 'off'
        }
    },
    {
        /*
         * The timeline arithmetic belongs to the turn, and only to the turn.
         *
         * Its eight transformers are each simple and only correct in a particular order, and that
         * order is what `services/turn.ts` exists to own. Every ordering bug this codebase has had
         * in a conversation came from a caller that reached for the transformers and arranged them
         * itself. `messageParts` is exempt because rendering a stored message is not running a
         * turn, and `ChatConversation` is the only thing that draws one.
         */
        files: ['src/**/*.{ts,tsx}'],
        ignores: [
            'src/services/turn.ts',
            'src/models/chat-timeline.ts',
            'src/models/chat-timeline.test.ts',
            'src/components/workspace/ChatConversation.tsx'
        ],
        rules: {
            'no-restricted-imports': [
                'error',
                {
                    patterns: [
                        {
                            group: ['**/models/chat-timeline', './chat-timeline'],
                            message:
                                'Run turns through services/turn.ts. The timeline transformers are only correct in the order it applies them.'
                        }
                    ]
                }
            ]
        }
    },
    {
        /*
         * The React rules, over the React.
         *
         * `reactHooks` is version 7, where `flat.recommended` is not two rules about hooks any more
         * — it is the React Compiler, eighteen rules that each put the file through the compiler's
         * own pipeline. Applied to `**` that ran over the thirteen end-to-end specs and the five
         * wdio configs as well, none of which contain a component, and it is the most expensive
         * thing in the lint. `reactRefresh` is here for the same reason: its subject is a module
         * Vite hot-reloads, and nothing outside `src` is one.
         */
        files: ['src/**/*.{ts,tsx}'],
        extends: [reactHooks.configs.flat.recommended, reactRefresh.configs.vite]
    },
    {
        files: ['vite.config.ts'],
        languageOptions: {globals: globals.node}
    }
)
