/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/theme.ts
 * Command: astryx theme build src/theme/theme.ts --out src/theme/gofer-theme.css
 * Generated: 2026-08-06T14:57:14.884Z
 */

import type {DefinedTheme} from '@astryxdesign/core/theme'
export declare const goferTheme: DefinedTheme
