/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/theme.ts
 * Command: astryx theme build src/theme/theme.ts --out src/theme/gofer-theme.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {}

declare module '@astryxdesign/core/ProgressBar' {
    interface ProgressBarVariantMap {
        accent: true
        success: true
        warning: true
        error: true
    }
}
