/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/theme.ts
 * Command: astryx theme build src/theme/theme.ts --out src/theme/gofer-theme.css
 * Generated: 2026-08-24T05:26:51.275Z
 */

import type {DefinedTheme} from '@astryxdesign/core/theme'
export declare const goferTheme: DefinedTheme
